### ISSUE TITLE
vim-mode-plus support

### ISSUE THREAD

**Issue by realh** [sQu1rr/vim-mode-zz#2]
I was pleased to find this plugin, I use ZZ a lot in real vim.

However, vim-mode is apparently deprecated in favour of vim-mode-plus. It's quite easy to make vim-mode-zz work with vim-mode-plus by changing the bindings so that `atom-text-editor.vim-mode` becomes `atom-text-editor.vim-mode-plus`. I don't know if you could make this plugin support both the vim plugins or would be willing to fork it to make a new plugin or whatever to officially support vim-mode-plus.

**Comment by sQu1rr** [comment]
I may look into it in my free time this/next week. feel free to create a PR if you find a way.
